# Use a base image with Python
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Copy the Python code, templates, &, session file into the container
COPY Automation.py /app/
COPY templates /app/templates
COPY Default_WA_personal /app/Default_WA_personal

# Install dependencies
RUN pip install --upgrade pip && \
    pip install -r req.txt && \
    playwright install && \
    playwright install-deps

# Set the entry point for the container
CMD ["python3", "TwitterTrendingAPI.py"]